site:
  url: https://www.ucaiug.io/getting-started-with-cim
  base_url: /getting-started-with-cim
  # start_page: ROOT::index.adoc
content:
  sources:
    - url: '' # Could source from other repo URLs, blank means local
      branches: HEAD
      start_paths: src
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
#  extensions:
#    - asciidoctor-kroki
output:
  clean: true
  dir: build/site
ui:
 bundle:
   url: https://github.com/cimug-org/antora-ui-cimug-spec/releases/download/v0.1.0/ui-bundle.zip