name: Build and publish Antora site

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Antora
        run: npm install -g @antora/cli @antora/site-generator

      - name: Install dependencies
        run: npm install

      - name: Build site with Antora
        run: antora antora-playbook.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            publish_dir: ./build/site
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: master